[env]
TERM = 'xterm-256color'

[window]
padding.x = 8
padding.y = 8
decorations = "Buttonless"

[font]

normal.family      = "Hack Nerd Font"
bold.family        = "Hack Nerd Font"
italic.family      = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

size               = 13
offset.x           = 0
offset.y           = 2

[cursor]
style.shape        = 'Underline'
thickness          = 0.25

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

#[colors.cursor]
#cursor = '#c8d3f5'
#text = '#222436'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'

