[window]
padding.x = 8
padding.y = 8
decorations = "Buttonless"

[font]

normal.family      = "Hack Nerd Font"
bold.family        = "Hack Nerd Font"
italic.family      = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

size               = 13
offset.x           = 0
offset.y           = 4

[colors]
primary.background = '0x1a1b26'
primary.foreground = '0xc0caf5'
normal.black       = '0x15161e'
normal.red         = '0xf7768e'
normal.green       = '0x9ece6a'
normal.yellow      = '0xe0af68'
normal.blue        = '0x7aa2f7'
normal.magenta     = '0xbb9af7'
normal.cyan        = '0x7dcfff'
normal.white       = '0xa9b1d6'
bright.black       = '0x414868'
bright.red         = '0xf7768e'
bright.green       = '0x9ece6a'
bright.yellow      = '0xe0af68'
bright.blue        = '0x7aa2f7'
bright.magenta     = '0xbb9af7'
bright.cyan        = '0x7dcfff'
bright.white       = '0xc0caf5'

[cursor]
style.shape        = 'Underline'
thickness          = 0.25
